title: "An eerie sight"
description: "Pocos ven lo que somos, pero todos ven lo que aparentamos."
show_downloads: false

# URL de tu sitio
url: "https://ritavratask.github.io"
baseurl: "" 

# Datos de perfil
author: "Rata Trataski"
linkedin_username: "silvia-hernández-sánchez-899022121" 

# Configuración del logo (Asegúrate de que el nombre sea matrix.jpeg)
logo: "/assets/img/matrix.jpeg"

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
