title: "El sitio de la Silvia"
description: "Blog de ciberseguridad"
tagline: 'Escribiendo mis pensamientos sobre inteligencia, alguna investigacion que haga y otras cosas"
remote_theme: pages-themes/midnight@v0.2.0
plugins: - jekyll-remote-theme # add this line to the plugins list if you already have one
