title: "An eerie sight"
description: "Escribiendo mis pensamientos sobre inteligencia, malware, cibercriminalidad, el futuro del trabajo humano y alguna que otra cosa"

# URL de tu sitio (AÃ±ade esto para que carguen los estilos CSS)
url: "https://ritavratask.github.io"
baseurl: "" 

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
