title: "El sitio de la Silvia"
description: "Blog de ciberseguridad"
tagline: "Escribiendo mis pensamientos sobre inteligencia, alguna investigacion que haga y otras cosas"

# El tema Midnight de GitHub
remote_theme: pages-themes/midnight@v0.2.0

# Correcci√≥n de la lista de plugins
plugins:
  - jekyll-remote-theme
