title: "An eerie sight"
description: "Blog sobre cosas"
tagline: "Escribiendo mis pensamientos sobre inteligencia, alguna investigacion que haga y otras cosas"

# URL de tu sitio (AÃ±ade esto para que carguen los estilos CSS)
url: "https://ritavratask.github.io"
baseurl: "" 

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
