title: "An eerie sight"
description: "Nada en la vida debe ser temido, solo comprendido. Ahora es el momento de comprender m치s, para que podamos temer menos"

# URL de tu sitio (A침ade esto para que carguen los estilos CSS)
url: "https://ritavratask.github.io"
baseurl: "" 

# Datos de perfil
author: "Rata Trataski"
linkedin_username: "silvia-hern치ndez-s치nchez-899022121" 

logo: "/assets/img/matrix.jpeg"

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
