title: "An eerie sight"
description: "Escribiendo mis pensamientos sobre inteligencia, malware, cibercriminalidad, el futuro del trabajo humano y alguna que otra cosa"

# URL de tu sitio (Añade esto para que carguen los estilos CSS)
url: "https://ritavratask.github.io"
baseurl: "" 

# Datos de perfil
author: "Rata Trataski"
linkedin_username: "silvia-hernández-sánchez-899022121" 

logo: "/assets/img/matrix.jpeg"

remote_theme: pages-themes/midnight@v0.2.0

plugins:
  - jekyll-remote-theme
