baseURL = 'https://ritavratask.github.io/'
languageCode = 'es-es'
title = 'El sitio de la Silvia'
theme = "hugo-brewm"

# Forzamos la carpeta de contenido
contentDir = 'content'

[params]
    # Quitamos el "/" y dejamos solo "posts"
    mainSections = ["posts"]
    buildFuture = true
    buildDrafts = true
