baseURL = 'https://ritavratask.github.io/'
languageCode = 'es-es'
title = 'El sitio de la Silvia'
theme = "hugo-brewm"

[params]
    # Esta l√≠nea es la que quita al gato y pone tus posts
    mainSections = ["posts"]
